# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12WwA18LIXU_eE6-sGyGrY55du9jhyPs6
"""

import requests
import pandas as pd


url = 'https://berita-indo-api-next.vercel.app/api/cnn-news/teknologi'
response = requests.get(url)


if response.status_code == 200:
    data_json = response.json()
    data = data_json['data']
else:
    print("Request tidak berhasil.")

df = pd.DataFrame(data)

df['isoDate'] = pd.to_datetime(df['isoDate'])

print(df)